module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  barcode_count_field: 0
  basic_auth: 0
  block: 0
  breakpoint: 0
  coffee: 0
  config: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  image: 0
  kint: 0
  link: 0
  log: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  purge: 0
  purge_purger_http: 0
  purge_tokens: 0
  rest: 0
  rest_is_logged_in: 0
  restui: 0
  serialization: 0
  sparkpost: 0
  system: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
